### ISSUE TITLE
segmentation fault in tcd_decode_tile

### ISSUE THREAD

**Issue by jwilk** [jwilk/pdf2djvu#87]
**Issue reported by @jsbien**:

*What steps will reproduce the problem?*

1. Download the first volume of OED from https://archive.org/download/oed01arch/oed01arch.pdf
2. Call pdf2djvu on the file using only `-o` option.

*What is the expected output? What do you see instead?*

There is a lot of `Bogus memory allocation size` messages and, during processing of page #212, "Segmentation fault".

*What version of the product are you using? On what operating system?*

pdf2djvu 0.7.17 (DjVuLibre 3,5,25, poppler 0.18.4, GraphicsMagick++ 1.s.15, GNOME XSLT 1.1.26, GNOME XML 2.9.1), Debian sid.

**Comment by jwilk** [comment]
As a data point, I've successfully converted this PDF using on Debian jessie on amd64.
Peak virtual memory use was over 3 GB. :(

**Comment by jwilk** [comment]
I've successfully converted the file on these systems:

* Debian jessie: pdf2djvu 0.7.17 (DjVuLibre 3.5.25, Poppler 0.26.5, GraphicsMagick++ 1.3.20, GNOME XSLT 1.1.28, GNOME XML 2.9.1)
* Debian stretch: pdf2djvu 0.9.4 (DjVuLibre 3.5.27, Poppler 0.48.0, GraphicsMagick++ 1.3.25, Exiv2 0.25)

both on i386 and amd64.

I guess the bug was in Poppler (or a dependent library), and it was fixed in the mean time.
I'm closing the bug under this assumption.

@jsbien, if you can still reproduce the crash, let me now, and I'll reopen the bug.

**Comment by jsbien** [comment]
Still unable to convert on Debian stretch, but for a different reason: 8 GB of memory appears insufficient.

**Comment by jwilk** [comment]
The exorbitant memory use is caused by memory leak in `MutedRenderer::drawChar`.
Let's track this in #63.
